ignore:
  - build/
  - jest.setup.js
scanners:
  - "@continuous-security/scanner-javascript-js-x-ray"
  - "@continuous-security/scanner-javascript-njsscan"
  - "@continuous-security/scanner-javascript-npm-audit"
  - "@continuous-security/scanner-bearer"
