module.exports = {
  pythonBanditReport: Buffer.from(JSON.stringify({
    errors: [],
    generated_at: '2023-04-03T13:06:25Z',
    metrics: {
      '/target/main.py': {
        'CONFIDENCE.HIGH': 1,
        'CONFIDENCE.LOW': 0,
        'CONFIDENCE.MEDIUM': 1,
        'CONFIDENCE.UNDEFINED': 0,
        'SEVERITY.HIGH': 0,
        'SEVERITY.LOW': 2,
        'SEVERITY.MEDIUM': 0,
        'SEVERITY.UNDEFINED': 0,
        loc: 9,
        nosec: 0,
        skipped_tests: 0,
      },
      _totals: {
        'CONFIDENCE.HIGH': 1,
        'CONFIDENCE.LOW': 0,
        'CONFIDENCE.MEDIUM': 1,
        'CONFIDENCE.UNDEFINED': 0,
        'SEVERITY.HIGH': 0,
        'SEVERITY.LOW': 2,
        'SEVERITY.MEDIUM': 0,
        'SEVERITY.UNDEFINED': 0,
        loc: 9,
        nosec: 0,
        skipped_tests: 0,
      },
    },
    results: [
      {
        code: '3     print(\'thing\')\\n4   except:\\n5     pass\\n6 \\n',
        col_offset: 2,
        end_col_offset: 8,
        filename: '/target/main.py',
        issue_confidence: 'HIGH',
        issue_cwe: {
          id: 703,
          link: 'https://cwe.mitre.org/data/definitions/703.html',
        },
        issue_severity: 'LOW',
        issue_text: 'Try, Except, Pass detected.',
        line_number: 4,
        line_range: [
          4,
          5,
        ],
        more_info: 'https://bandit.readthedocs.io/en/1.7.5/plugins/b110_try_except_pass.html',
        test_id: 'B110',
        test_name: 'try_except_pass',
      },
      {
        code: '7 def login(username, password):\\n8   if password == \'password\':\\n9     return True\\n',
        col_offset: 17,
        end_col_offset: 27,
        filename: '/target/main.py',
        issue_confidence: 'MEDIUM',
        issue_cwe: {
          id: 259,
          link: 'https://cwe.mitre.org/data/definitions/259.html',
        },
        issue_severity: 'LOW',
        issue_text: 'Possible hardcoded password: \'password\'',
        line_number: 8,
        line_range: [
          8,
        ],
        more_info: 'https://bandit.readthedocs.io/en/1.7.5/plugins/b105_hardcoded_password_string.html',
        test_id: 'B105',
        test_name: 'hardcoded_password_string',
      },
    ],
  })),
};
