name: 'Test and Publish: Scanners'

on:
  push:
    branches:
      - main
      - development
    paths:
      - scanners/**
      - .github/workflows/publish-scanners.yml
  pull_request:

concurrency:
  group: "scanners"
  cancel-in-progress: true

jobs:
  find-scanners:
    runs-on: ubuntu-latest
    outputs:
      scanners: ${{ steps.scanners.outputs.scanners }}
    steps:
      - uses: actions/checkout@v3
      - id: scanners
        run: echo "scanners=$(ls -1 ./scanners | jq -Rnrc '[inputs] | map(select(. != "_base"))')" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: [find-scanners]
    strategy:
      matrix:
        scanner: ${{ fromJSON(needs.find-scanners.outputs.scanners) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: scanners/${{ matrix.scanner }}
      - run: npm run lint
        working-directory: scanners/${{ matrix.scanner }}

  test:
    runs-on: ubuntu-latest
    needs: [find-scanners]
    strategy:
      matrix:
        scanner: ${{ fromJSON(needs.find-scanners.outputs.scanners) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: scanners/${{ matrix.scanner }}
      - run: npm test
        working-directory: scanners/${{ matrix.scanner }}
      - run: npm run test:integration --if-present
        working-directory: scanners/${{ matrix.scanner }}

  audit:
    runs-on: ubuntu-latest
    needs: [find-scanners]
    strategy:
      matrix:
        scanner: ${{ fromJSON(needs.find-scanners.outputs.scanners) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm audit
        working-directory: scanners/${{ matrix.scanner }}

  publish:
    runs-on: ubuntu-latest
    needs: [find-scanners, lint, test, audit]
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        scanner: ${{ fromJSON(needs.find-scanners.outputs.scanners) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: scanners/${{ matrix.scanner }}
      - run: bash ../../.github/scripts/npm-publish.sh
        working-directory: scanners/${{ matrix.scanner }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
