name: quality checks

on:
  push:
    branches:
      - main
      - development
  pull_request:

concurrency:
  group: quality-checks-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: application/package-lock.json
      - run: npm ci
        working-directory: application/
      - run: npm audit
        working-directory: application/
      - run: npm run lint
        working-directory: application/
      - run: npm test
        working-directory: application/

  find-scanners:
    runs-on: ubuntu-latest
    outputs:
      scanners: ${{ steps.scanners.outputs.scanners }}
    steps:
      - uses: actions/checkout@v3
      - id: scanners
        run: echo "scanners=$(ls -1 ./scanners | jq -Rnrc '[inputs] | map(select(. != "_base"))')" >> $GITHUB_OUTPUT

  scanners:
    name: scanner/${{ matrix.scanner }}
    runs-on: ubuntu-latest
    needs: [find-scanners]
    strategy:
      matrix:
        scanner: ${{ fromJSON(needs.find-scanners.outputs.scanners) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: scanners/${{ matrix.scanner }}/package-lock.json
      - name: install
        run: npm ci
        working-directory: scanners/${{ matrix.scanner }}/
      - name: audit
        run: npm audit
        working-directory: scanners/${{ matrix.scanner }}/
      - name: lint
        run: npm run lint
        working-directory: scanners/${{ matrix.scanner }}/
      - name: unit test
        run: npm test
        working-directory: scanners/${{ matrix.scanner }}/
      - name: integration test
        run: npm run test:integration --if-present
        working-directory: scanners/${{ matrix.scanner }}/
