name: quality checks

on:
  push:
    branches:
      - main
      - development
  pull_request:

permissions:
  pull-requests: write

concurrency:
  group: quality-checks-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: check and correct pull request
        uses: actions/github-script@v6
        with:
          script: |
            const {owner, repo} = context.repo;
            const pull_number = context.payload.pull_request.number;
            
            const {data: pr} = await github.rest.pulls.get({owner, repo, pull_number});
            
            // Checking you are using the right target.
            if (pr.base.ref === 'main' && pr.head.ref !== 'development') {
              console.log(`Attempting to merge ${pr.head.ref} into main, switching target to development.`);
              await github.rest.pulls.update({owner, repo, pull_number, base: 'development'});
              pr.base.ref = 'development';
            }
            
            // Checking you've given your PR the right name.
            if (pr.base.ref === 'development') {
              if (!['feat: ', 'fix: ', 'chore: '].some(t => pr.title.startsWith(t))) {
                throw new Error('Pull request title must start with feat:, fix: or chore:');
              }
            }
            
            if (pr.base.ref === 'main') {
              if (!pr.title.match(/^Release [0-9]+\.[0-9]+\.[0-9]+$/)) {
                throw new Error('Pull requests targeting main must have a title "Release x.x.x"');
              }
            }

  application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: application/package-lock.json
      - run: npm ci
        working-directory: application/
      - run: npm audit
        working-directory: application/
      - run: npm run lint
        working-directory: application/
      - run: npm test
        working-directory: application/
      - run: npm run build
        working-directory: application/
      - uses: actions/upload-artifact@v3
        with:
          name: application
          path: |
            application/
            !application/node_modules

  enumerate-scanners:
    name: scanner / enumerate
    runs-on: ubuntu-latest
    outputs:
      scanners: ${{ steps.scanners.outputs.scanners }}
    steps:
      - uses: actions/checkout@v3
      - id: scanners
        run: echo "scanners=$(ls -1 ./scanners | jq -Rnrc '[inputs] | map(select(. != "_base"))')" >> $GITHUB_OUTPUT

  scanners:
    name: scanner / ${{ matrix.scanner }}
    runs-on: ubuntu-latest
    needs: [ enumerate-scanners ]
    strategy:
      matrix:
        scanner: ${{ fromJSON(needs.enumerate-scanners.outputs.scanners) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: scanners/${{ matrix.scanner }}/package-lock.json
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: install
        run: npm ci
        working-directory: scanners/${{ matrix.scanner }}/
      - name: audit
        run: npm audit
        working-directory: scanners/${{ matrix.scanner }}/
      - name: lint
        run: npm run lint
        working-directory: scanners/${{ matrix.scanner }}/
      - name: unit test
        run: npm test
        working-directory: scanners/${{ matrix.scanner }}/
      - name: integration test
        run: npm run test:integration --if-present
        working-directory: scanners/${{ matrix.scanner }}/
      - run: npm run build
        working-directory: scanners/${{ matrix.scanner }}/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.scanner }}
          path: |
            scanners/${{ matrix.scanner }}/
            !scanners/${{ matrix.scanner }}/node_modules

  application-check:
    name: application / scan
    runs-on: ubuntu-latest
    needs: [ application, scanners ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: application/package-lock.json
      - uses: actions/download-artifact@v3
        with:
          path: artefacts/
      - run: tree artefacts/
#      - run: DEBUG=true continuous-security scan || (cat report.md >> $GITHUB_STEP_SUMMARY)
#        working-directory: application/

  scanner-check:
    name: scanner / scan / ${{ matrix.scanner }}
    runs-on: ubuntu-latest
    needs: [ application, scanners, enumerate-scanners ]
    strategy:
      matrix:
        scanner: ${{ fromJSON(needs.enumerate-scanners.outputs.scanners) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: scanners/${{ matrix.scanner }}/package-lock.json
      - uses: actions/download-artifact@v3
        with:
          path: artefacts/
      - run: tree artefacts/
#      - run: DEBUG=true continuous-security scan || (cat report.md >> $GITHUB_STEP_SUMMARY)
#        working-directory: scanners/${{ matrix.scanner }}/
