name: 'Test: Application'

on:
  push:
    paths:
      - application/**
      - .github/workflows/test-application.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: application/
      - run: npm run lint
        working-directory: application/
      - run: npm test
        working-directory: application/
